storage:
  base_path: "data"

downloader:
  # 全局股票池。默认使用这个指定的列表。
  # 如果想下载全市场，请将下一行取消注释，并注释掉列表。
  # symbols: "all"
  symbols: ["600519.SH", "002023.SZ"]

tasks:
  - name: "更新A股列表"
    enabled: true
    type: "stock_list"
    update_strategy: "cooldown"
    update_interval_hours: 12

  - name: "日K线-前复权"
    enabled: true
    type: "daily"
    adjust: "qfq"
    update_strategy: "incremental"
    date_col: "trade_date"  # 明确指定日期列

  - name: "日K线-不复权"
    enabled: true
    type: "daily"
    adjust: "none"
    update_strategy: "incremental"
    date_col: "trade_date"  # 明确指定日期列

  - name: "每日指标"
    enabled: true
    type: "daily_basic" 
    # 这个任务本质上是增量的，但其逻辑在处理器内部实现
    # 我们可以不指定 update_strategy，或者自定义一个
    update_strategy: "incremental"
    date_col: "trade_date"

  - name: "财务报表-利润表"
    enabled: true
    type: "financials"
    statement_type: "income" # 对应 fetch_income
    update_strategy: "incremental"
    date_col: "ann_date"

  - name: "财务报表-资产负债表"
    enabled: true
    type: "financials"
    statement_type: "balancesheet" # 对应 fetch_balancesheet
    update_strategy: "incremental"
    date_col: "ann_date"

  - name: "财务报表-现金流量表"
    enabled: true
    type: "financials"
    statement_type: "cashflow" # 对应 fetch_cashflow
    update_strategy: "incremental"
    date_col: "ann_date"