# 数据库配置 (用于新架构)
database:
  path: "/Users/yapex/workspace/stock_data/stock.db"

# 下载器配置
downloader:
  max_producers: 2
  max_consumers: 1
  producer_queue_size: 1000
  data_queue_size: 500
  retry_policy:
    max_retries: 3
    base_delay: 1.0
    max_delay: 60.0
    backoff_factor: 2.0
    jitter: true

# 消费者配置
consumer:
  batch_size: 100
  flush_interval: 30.0
  max_retries: 3

# 获取器配置
fetcher:
  rate_limit: 195

# 并发控制
concurrency:
  max_concurrent_tasks: 1

# 任务模板定义：只定义任务的核心类型和参数
tasks:
  update_stock_list:
    name: "更新A股列表"
    type: "stock_list"
    
  daily_qfq:
    name: "日K线-前复权"
    type: "daily"
    adjust: "qfq"
    date_col: "trade_date"
    
  daily_none:
    name: "日K线-不复权"
    type: "daily"
    adjust: "none"
    date_col: "trade_date"
    
  daily_basic:
    name: "每日指标"
    type: "daily_basic"
    date_col: "trade_date"
    
  financial_income:
    name: "财务报表-利润表"
    type: "financials"
    statement_type: "income"
    date_col: "ann_date"
    
  financial_balance:
    name: "财务报表-资产负债表"
    type: "financials"
    statement_type: "balancesheet"
    date_col: "ann_date"
    
  financial_cashflow:
    name: "财务报表-现金流量表"
    type: "financials"
    statement_type: "cashflow"
    date_col: "ann_date"

# 组配置：引用任务名称列表
groups:
  default:
    description: "默认组 - 核心股票的完整数据下载"
    symbols: ["600519", "002023", "600276", "600612", 
      "000333", "002415", "000895", "603288", "600900",
      "601100", "603568", "600636", "000651", "600570",
      "000858"]
    tasks: ["update_stock_list", "daily_qfq", "daily_none", "daily_basic", "financial_income", "financial_balance", "financial_cashflow"]
    
  all:
    description: "全股票完整数据下载（包含日K线和财务数据）"
    symbols: "all"
    tasks: ["update_stock_list", "daily_qfq", "daily_none", "daily_basic", "financial_income", "financial_balance", "financial_cashflow"]
    
  daily:
    description: "日K线数据 - 所有股票"
    symbols: "all"
    tasks: ["update_stock_list", "daily_qfq", "daily_none", "daily_basic"]
    
  financial:
    description: "财务报表数据 - 所有股票"
    symbols: "all"
    tasks: ["update_stock_list", "financial_income", "financial_balance", "financial_cashflow"]
    
  quick:
    description: "快速测试组 - 仅股票列表和基础日K线"
    symbols: ["600519", "000001"]
    tasks: ["financial_income", "financial_balance", "financial_cashflow"]
