[project]
name = "stock-downloader"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "pyarrow>=21.0.0",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "schedule>=1.2.2",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
    "tushare>=1.4.21",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "ipywidgets>=8.1.7",
    "nbformat>=5.10.4",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
