[stock_basic]
table_name = "stock_basic"
primary_key = [
    "ts_code",
]
description = "股票基本信息表字段"
api_method = "stock_basic"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "symbol", type = "TEXT" },
    { name = "name", type = "TEXT" },
    { name = "area", type = "TEXT" },
    { name = "industry", type = "TEXT" },
    { name = "cnspell", type = "TEXT" },
    { name = "market", type = "TEXT" },
    { name = "list_date", type = "TEXT" },
    { name = "act_name", type = "TEXT" },
    { name = "act_ent_type", type = "TEXT" },
]

[stock_daily]
table_name = "stock_daily"
primary_key = [
    "ts_code",
    "trade_date",
]
date_col = "trade_date"
description = "股票日线数据字段"
api_method = "daily"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "trade_date", type = "TEXT" },
    { name = "open", type = "TEXT" },
    { name = "high", type = "TEXT" },
    { name = "low", type = "TEXT" },
    { name = "close", type = "TEXT" },
    { name = "pre_close", type = "TEXT" },
    { name = "change", type = "TEXT" },
    { name = "pct_chg", type = "TEXT" },
    { name = "vol", type = "TEXT" },
    { name = "amount", type = "TEXT" },
]

[stock_adj_qfq]
table_name = "stock_adj_qfq"
primary_key = [
    "ts_code",
    "trade_date",
]
date_col = "trade_date"
description = "复权行情数据字段"
api_method = "pro_bar"
base_object = "ts"
required_params = { adj = "qfq" }
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "trade_date", type = "TEXT" },
    { name = "open", type = "REAL" },
    { name = "high", type = "REAL" },
    { name = "low", type = "REAL" },
    { name = "close", type = "REAL" },
    { name = "pre_close", type = "REAL" },
    { name = "change", type = "REAL" },
    { name = "pct_chg", type = "REAL" },
    { name = "vol", type = "REAL" },
    { name = "amount", type = "REAL" },
]

[daily_basic]
table_name = "daily_basic"
primary_key = [
    "ts_code",
    "trade_date",
]
date_col = "trade_date"
description = "获取全部股票每日重要的基本面指标"
api_method = "daily_basic"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "trade_date", type = "TEXT" },
    { name = "close", type = "TEXT" },
    { name = "turnover_rate", type = "TEXT" },
    { name = "turnover_rate_f", type = "TEXT" },
    { name = "volume_ratio", type = "TEXT" },
    { name = "pe", type = "TEXT" },
    { name = "pe_ttm", type = "TEXT" },
    { name = "pb", type = "TEXT" },
    { name = "ps", type = "TEXT" },
    { name = "ps_ttm", type = "TEXT" },
    { name = "dv_ratio", type = "TEXT" },
    { name = "dv_ttm", type = "TEXT" },
    { name = "total_share", type = "TEXT" },
    { name = "float_share", type = "TEXT" },
    { name = "free_share", type = "TEXT" },
    { name = "total_mv", type = "TEXT" },
    { name = "circ_mv", type = "TEXT" },
]

[income]
table_name = "income"
primary_key = [
    "ts_code",
    "ann_date",
]
date_col = "f_ann_date"
description = "利润表字段"
api_method = "income"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "ann_date", type = "TEXT" },
    { name = "f_ann_date", type = "TEXT" },
    { name = "end_date", type = "TEXT" },
    { name = "report_type", type = "TEXT" },
    { name = "comp_type", type = "TEXT" },
    { name = "end_type", type = "TEXT" },
    { name = "basic_eps", type = "REAL" },
    { name = "diluted_eps", type = "REAL" },
    { name = "total_revenue", type = "REAL" },
    { name = "revenue", type = "REAL" },
    { name = "int_income", type = "REAL" },
    { name = "prem_earned", type = "TEXT" },
    { name = "comm_income", type = "TEXT" },
    { name = "n_commis_income", type = "TEXT" },
    { name = "n_oth_income", type = "TEXT" },
    { name = "n_oth_b_income", type = "TEXT" },
    { name = "prem_income", type = "TEXT" },
    { name = "out_prem", type = "TEXT" },
    { name = "une_prem_reser", type = "TEXT" },
    { name = "reins_income", type = "TEXT" },
    { name = "n_sec_tb_income", type = "TEXT" },
    { name = "n_sec_uw_income", type = "TEXT" },
    { name = "n_asset_mg_income", type = "TEXT" },
    { name = "oth_b_income", type = "TEXT" },
    { name = "fv_value_chg_gain", type = "REAL" },
    { name = "invest_income", type = "REAL" },
    { name = "ass_invest_income", type = "TEXT" },
    { name = "forex_gain", type = "TEXT" },
    { name = "total_cogs", type = "REAL" },
    { name = "oper_cost", type = "REAL" },
    { name = "int_exp", type = "REAL" },
    { name = "comm_exp", type = "REAL" },
    { name = "biz_tax_surchg", type = "REAL" },
    { name = "sell_exp", type = "REAL" },
    { name = "admin_exp", type = "REAL" },
    { name = "fin_exp", type = "REAL" },
    { name = "assets_impair_loss", type = "TEXT" },
    { name = "prem_refund", type = "TEXT" },
    { name = "compens_payout", type = "TEXT" },
    { name = "reser_insur_liab", type = "TEXT" },
    { name = "div_payt", type = "TEXT" },
    { name = "reins_exp", type = "TEXT" },
    { name = "oper_exp", type = "TEXT" },
    { name = "compens_payout_refu", type = "TEXT" },
    { name = "insur_reser_refu", type = "TEXT" },
    { name = "reins_cost_refund", type = "TEXT" },
    { name = "other_bus_cost", type = "TEXT" },
    { name = "operate_profit", type = "REAL" },
    { name = "non_oper_income", type = "REAL" },
    { name = "non_oper_exp", type = "REAL" },
    { name = "nca_disploss", type = "TEXT" },
    { name = "total_profit", type = "REAL" },
    { name = "income_tax", type = "REAL" },
    { name = "n_income", type = "REAL" },
    { name = "n_income_attr_p", type = "REAL" },
    { name = "minority_gain", type = "REAL" },
    { name = "oth_compr_income", type = "REAL" },
    { name = "t_compr_income", type = "REAL" },
    { name = "compr_inc_attr_p", type = "REAL" },
    { name = "compr_inc_attr_m_s", type = "REAL" },
    { name = "ebit", type = "REAL" },
    { name = "ebitda", type = "REAL" },
    { name = "insurance_exp", type = "TEXT" },
    { name = "undist_profit", type = "TEXT" },
    { name = "distable_profit", type = "TEXT" },
    { name = "rd_exp", type = "REAL" },
    { name = "fin_exp_int_exp", type = "REAL" },
    { name = "fin_exp_int_inc", type = "REAL" },
    { name = "transfer_surplus_rese", type = "TEXT" },
    { name = "transfer_housing_imprest", type = "TEXT" },
    { name = "transfer_oth", type = "TEXT" },
    { name = "adj_lossgain", type = "TEXT" },
    { name = "withdra_legal_surplus", type = "TEXT" },
    { name = "withdra_legal_pubfund", type = "TEXT" },
    { name = "withdra_biz_devfund", type = "TEXT" },
    { name = "withdra_rese_fund", type = "TEXT" },
    { name = "withdra_oth_ersu", type = "TEXT" },
    { name = "workers_welfare", type = "TEXT" },
    { name = "distr_profit_shrhder", type = "TEXT" },
    { name = "prfshare_payable_dvd", type = "TEXT" },
    { name = "comshare_payable_dvd", type = "TEXT" },
    { name = "capit_comstock_div", type = "TEXT" },
    { name = "continued_net_profit", type = "REAL" },
    { name = "update_flag", type = "TEXT" },
]

[balance_sheet]
table_name = "balance_sheet"
primary_key = [
    "ts_code",
    "ann_date",
]
date_col = "f_ann_date"
description = "资产负债表字段"
api_method = "balancesheet"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "ann_date", type = "TEXT" },
    { name = "f_ann_date", type = "TEXT" },
    { name = "end_date", type = "TEXT" },
    { name = "report_type", type = "TEXT" },
    { name = "comp_type", type = "TEXT" },
    { name = "end_type", type = "TEXT" },
    { name = "total_share", type = "REAL" },
    { name = "cap_rese", type = "REAL" },
    { name = "undistr_porfit", type = "REAL" },
    { name = "surplus_rese", type = "REAL" },
    { name = "special_rese", type = "TEXT" },
    { name = "money_cap", type = "REAL" },
    { name = "trad_asset", type = "REAL" },
    { name = "notes_receiv", type = "REAL" },
    { name = "accounts_receiv", type = "REAL" },
    { name = "oth_receiv", type = "REAL" },
    { name = "prepayment", type = "REAL" },
    { name = "div_receiv", type = "TEXT" },
    { name = "int_receiv", type = "TEXT" },
    { name = "inventories", type = "REAL" },
    { name = "amor_exp", type = "TEXT" },
    { name = "nca_within_1y", type = "REAL" },
    { name = "sett_rsrv", type = "TEXT" },
    { name = "loanto_oth_bank_fi", type = "REAL" },
    { name = "premium_receiv", type = "TEXT" },
    { name = "reinsur_receiv", type = "TEXT" },
    { name = "reinsur_res_receiv", type = "TEXT" },
    { name = "pur_resale_fa", type = "REAL" },
    { name = "oth_cur_assets", type = "REAL" },
    { name = "total_cur_assets", type = "REAL" },
    { name = "fa_avail_for_sale", type = "TEXT" },
    { name = "htm_invest", type = "TEXT" },
    { name = "lt_eqt_invest", type = "TEXT" },
    { name = "invest_real_estate", type = "REAL" },
    { name = "time_deposits", type = "TEXT" },
    { name = "oth_assets", type = "TEXT" },
    { name = "lt_rec", type = "TEXT" },
    { name = "fix_assets", type = "REAL" },
    { name = "cip", type = "REAL" },
    { name = "const_materials", type = "TEXT" },
    { name = "fixed_assets_disp", type = "TEXT" },
    { name = "produc_bio_assets", type = "TEXT" },
    { name = "oil_and_gas_assets", type = "TEXT" },
    { name = "intan_assets", type = "REAL" },
    { name = "r_and_d", type = "REAL" },
    { name = "goodwill", type = "TEXT" },
    { name = "lt_amor_exp", type = "REAL" },
    { name = "defer_tax_assets", type = "REAL" },
    { name = "decr_in_disbur", type = "REAL" },
    { name = "oth_nca", type = "REAL" },
    { name = "total_nca", type = "REAL" },
    { name = "cash_reser_cb", type = "TEXT" },
    { name = "depos_in_oth_bfi", type = "TEXT" },
    { name = "prec_metals", type = "TEXT" },
    { name = "deriv_assets", type = "TEXT" },
    { name = "rr_reins_une_prem", type = "TEXT" },
    { name = "rr_reins_outstd_cla", type = "TEXT" },
    { name = "rr_reins_lins_liab", type = "TEXT" },
    { name = "rr_reins_lthins_liab", type = "TEXT" },
    { name = "refund_depos", type = "TEXT" },
    { name = "ph_pledge_loans", type = "TEXT" },
    { name = "refund_cap_depos", type = "TEXT" },
    { name = "indep_acct_assets", type = "TEXT" },
    { name = "client_depos", type = "TEXT" },
    { name = "client_prov", type = "TEXT" },
    { name = "transac_seat_fee", type = "TEXT" },
    { name = "invest_as_receiv", type = "TEXT" },
    { name = "total_assets", type = "REAL" },
    { name = "lt_borr", type = "TEXT" },
    { name = "st_borr", type = "TEXT" },
    { name = "cb_borr", type = "TEXT" },
    { name = "depos_ib_deposits", type = "REAL" },
    { name = "loan_oth_bank", type = "TEXT" },
    { name = "trading_fl", type = "TEXT" },
    { name = "notes_payable", type = "TEXT" },
    { name = "acct_payable", type = "REAL" },
    { name = "adv_receipts", type = "TEXT" },
    { name = "sold_for_repur_fa", type = "TEXT" },
    { name = "comm_payable", type = "TEXT" },
    { name = "payroll_payable", type = "REAL" },
    { name = "taxes_payable", type = "REAL" },
    { name = "int_payable", type = "TEXT" },
    { name = "div_payable", type = "TEXT" },
    { name = "oth_payable", type = "REAL" },
    { name = "acc_exp", type = "TEXT" },
    { name = "deferred_inc", type = "TEXT" },
    { name = "st_bonds_payable", type = "TEXT" },
    { name = "payable_to_reinsurer", type = "TEXT" },
    { name = "rsrv_insur_cont", type = "TEXT" },
    { name = "acting_trading_sec", type = "TEXT" },
    { name = "acting_uw_sec", type = "TEXT" },
    { name = "non_cur_liab_due_1y", type = "REAL" },
    { name = "oth_cur_liab", type = "REAL" },
    { name = "total_cur_liab", type = "REAL" },
    { name = "bond_payable", type = "TEXT" },
    { name = "lt_payable", type = "TEXT" },
    { name = "specific_payables", type = "TEXT" },
    { name = "estimated_liab", type = "TEXT" },
    { name = "defer_tax_liab", type = "REAL" },
    { name = "defer_inc_non_cur_liab", type = "TEXT" },
    { name = "oth_ncl", type = "TEXT" },
    { name = "total_ncl", type = "REAL" },
    { name = "depos_oth_bfi", type = "TEXT" },
    { name = "deriv_liab", type = "TEXT" },
    { name = "depos", type = "TEXT" },
    { name = "agency_bus_liab", type = "TEXT" },
    { name = "oth_liab", type = "TEXT" },
    { name = "prem_receiv_adva", type = "TEXT" },
    { name = "depos_received", type = "TEXT" },
    { name = "ph_invest", type = "TEXT" },
    { name = "reser_une_prem", type = "TEXT" },
    { name = "reser_outstd_claims", type = "TEXT" },
    { name = "reser_lins_liab", type = "TEXT" },
    { name = "reser_lthins_liab", type = "TEXT" },
    { name = "indept_acc_liab", type = "TEXT" },
    { name = "pledge_borr", type = "TEXT" },
    { name = "indem_payable", type = "TEXT" },
    { name = "policy_div_payable", type = "TEXT" },
    { name = "total_liab", type = "REAL" },
    { name = "treasury_share", type = "TEXT" },
    { name = "ordin_risk_reser", type = "REAL" },
    { name = "forex_differ", type = "TEXT" },
    { name = "invest_loss_unconf", type = "TEXT" },
    { name = "minority_int", type = "REAL" },
    { name = "total_hldr_eqy_exc_min_int", type = "REAL" },
    { name = "total_hldr_eqy_inc_min_int", type = "REAL" },
    { name = "total_liab_hldr_eqy", type = "REAL" },
    { name = "lt_payroll_payable", type = "TEXT" },
    { name = "oth_comp_income", type = "REAL" },
    { name = "oth_eqt_tools", type = "TEXT" },
    { name = "oth_eqt_tools_p_shr", type = "TEXT" },
    { name = "lending_funds", type = "TEXT" },
    { name = "acc_receivable", type = "TEXT" },
    { name = "st_fin_payable", type = "TEXT" },
    { name = "payables", type = "TEXT" },
    { name = "hfs_assets", type = "TEXT" },
    { name = "hfs_sales", type = "TEXT" },
    { name = "cost_fin_assets", type = "TEXT" },
    { name = "fair_value_fin_assets", type = "TEXT" },
    { name = "contract_assets", type = "TEXT" },
    { name = "contract_liab", type = "REAL" },
    { name = "accounts_receiv_bill", type = "REAL" },
    { name = "accounts_pay", type = "REAL" },
    { name = "oth_rcv_total", type = "REAL" },
    { name = "fix_assets_total", type = "REAL" },
    { name = "cip_total", type = "REAL" },
    { name = "oth_pay_total", type = "REAL" },
    { name = "long_pay_total", type = "TEXT" },
    { name = "debt_invest", type = "REAL" },
    { name = "oth_debt_invest", type = "TEXT" },
    { name = "update_flag", type = "TEXT" },
]

[cash_flow]
table_name = "cash_flow"
primary_key = [
    "ts_code",
    "ann_date",
]
date_col = "f_ann_date"
description = "现金流量表字段"
api_method = "cashflow"
base_object = "pro"
columns = [
    { name = "ts_code", type = "TEXT" },
    { name = "ann_date", type = "TEXT" },
    { name = "f_ann_date", type = "TEXT" },
    { name = "end_date", type = "TEXT" },
    { name = "comp_type", type = "TEXT" },
    { name = "report_type", type = "TEXT" },
    { name = "end_type", type = "TEXT" },
    { name = "net_profit", type = "REAL" },
    { name = "finan_exp", type = "REAL" },
    { name = "c_fr_sale_sg", type = "REAL" },
    { name = "recp_tax_rends", type = "TEXT" },
    { name = "n_depos_incr_fi", type = "REAL" },
    { name = "n_incr_loans_cb", type = "TEXT" },
    { name = "n_inc_borr_oth_fi", type = "TEXT" },
    { name = "prem_fr_orig_contr", type = "TEXT" },
    { name = "n_incr_insured_dep", type = "TEXT" },
    { name = "n_reinsur_prem", type = "TEXT" },
    { name = "n_incr_disp_tfa", type = "TEXT" },
    { name = "ifc_cash_incr", type = "REAL" },
    { name = "n_incr_disp_faas", type = "TEXT" },
    { name = "n_incr_loans_oth_bank", type = "TEXT" },
    { name = "n_cap_incr_repur", type = "TEXT" },
    { name = "c_fr_oth_operate_a", type = "REAL" },
    { name = "c_inf_fr_operate_a", type = "REAL" },
    { name = "c_paid_goods_s", type = "REAL" },
    { name = "c_paid_to_for_empl", type = "REAL" },
    { name = "c_paid_for_taxes", type = "REAL" },
    { name = "n_incr_clt_loan_adv", type = "REAL" },
    { name = "n_incr_dep_cbob", type = "REAL" },
    { name = "c_pay_claims_orig_inco", type = "TEXT" },
    { name = "pay_handling_chrg", type = "REAL" },
    { name = "pay_comm_insur_plcy", type = "TEXT" },
    { name = "oth_cash_pay_oper_act", type = "REAL" },
    { name = "st_cash_out_act", type = "REAL" },
    { name = "n_cashflow_act", type = "REAL" },
    { name = "oth_recp_ral_inv_act", type = "REAL" },
    { name = "c_disp_withdrwl_invest", type = "REAL" },
    { name = "c_recp_return_invest", type = "REAL" },
    { name = "n_recp_disp_fiolta", type = "REAL" },
    { name = "n_recp_disp_sobu", type = "TEXT" },
    { name = "stot_inflows_inv_act", type = "REAL" },
    { name = "c_pay_acq_const_fiolta", type = "REAL" },
    { name = "c_paid_invest", type = "REAL" },
    { name = "n_disp_subs_oth_biz", type = "TEXT" },
    { name = "oth_pay_ral_inv_act", type = "REAL" },
    { name = "n_incr_pledge_loan", type = "TEXT" },
    { name = "stot_out_inv_act", type = "REAL" },
    { name = "n_cashflow_inv_act", type = "REAL" },
    { name = "c_recp_borrow", type = "TEXT" },
    { name = "proc_issue_bonds", type = "TEXT" },
    { name = "oth_cash_recp_ral_fnc_act", type = "TEXT" },
    { name = "stot_cash_in_fnc_act", type = "TEXT" },
    { name = "free_cashflow", type = "REAL" },
    { name = "c_prepay_amt_borr", type = "TEXT" },
    { name = "c_pay_dist_dpcp_int_exp", type = "REAL" },
    { name = "incl_dvd_profit_paid_sc_ms", type = "REAL" },
    { name = "oth_cashpay_ral_fnc_act", type = "REAL" },
    { name = "stot_cashout_fnc_act", type = "REAL" },
    { name = "n_cash_flows_fnc_act", type = "REAL" },
    { name = "eff_fx_flu_cash", type = "REAL" },
    { name = "n_incr_cash_cash_equ", type = "REAL" },
    { name = "c_cash_equ_beg_period", type = "REAL" },
    { name = "c_cash_equ_end_period", type = "REAL" },
    { name = "c_recp_cap_contrib", type = "TEXT" },
    { name = "incl_cash_rec_saims", type = "TEXT" },
    { name = "uncon_invest_loss", type = "TEXT" },
    { name = "prov_depr_assets", type = "TEXT" },
    { name = "depr_fa_coga_dpba", type = "REAL" },
    { name = "amort_intang_assets", type = "REAL" },
    { name = "lt_amort_deferred_exp", type = "REAL" },
    { name = "decr_deferred_exp", type = "TEXT" },
    { name = "incr_acc_exp", type = "TEXT" },
    { name = "loss_disp_fiolta", type = "REAL" },
    { name = "loss_scr_fa", type = "REAL" },
    { name = "loss_fv_chg", type = "REAL" },
    { name = "invest_loss", type = "REAL" },
    { name = "decr_def_inc_tax_assets", type = "REAL" },
    { name = "incr_def_inc_tax_liab", type = "REAL" },
    { name = "decr_inventories", type = "REAL" },
    { name = "decr_oper_payable", type = "REAL" },
    { name = "incr_oper_payable", type = "REAL" },
    { name = "others", type = "TEXT" },
    { name = "im_net_cashflow_oper_act", type = "REAL" },
    { name = "conv_debt_into_cap", type = "TEXT" },
    { name = "conv_copbonds_due_within_1y", type = "TEXT" },
    { name = "fa_fnc_leases", type = "TEXT" },
    { name = "im_n_incr_cash_equ", type = "REAL" },
    { name = "net_dism_capital_add", type = "TEXT" },
    { name = "net_cash_rece_sec", type = "TEXT" },
    { name = "credit_impa_loss", type = "REAL" },
    { name = "use_right_asset_dep", type = "REAL" },
    { name = "oth_loss_asset", type = "TEXT" },
    { name = "end_bal_cash", type = "REAL" },
    { name = "beg_bal_cash", type = "REAL" },
    { name = "end_bal_cash_equ", type = "REAL" },
    { name = "beg_bal_cash_equ", type = "REAL" },
    { name = "update_flag", type = "TEXT" },
]

[trade_cal]
table_name = "trade_cal"
primary_key = [
    "exchange",
    "cal_date",
]
date_col = "cal_date"
description = "交易日历"
api_method = "trade_cal"
base_object = "pro"
required_params = { exchange = "SSE" }
columns = [
    { name = "exchange", type = "TEXT" },
    { name = "cal_date", type = "TEXT" },
    { name = "is_open", type = "INTEGER" },
    { name = "pretrade_date", type = "TEXT" },
]
